name: Receive PR

# read-only repo token
# no access to secrets
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:        
      - uses: actions/checkout@v2

      # imitation of a build process
      - name: Build
        run: echo "Build"

      - name: Save PR number
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/NR
      - name: Save PR branch name
        run: |
          mkdir -p ./pr
          echo ${{ github.event.pull_request.head.ref }} > ./pr/BRANCH
      - uses: actions/upload-artifact@v4
        with:
          name: pr
          path: pr/
